# Generated by Django 4.2.2 on 2023-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="name_game", max_length=50, null=True),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        db_column="quantity_game", max_length=50, null=True
                    ),
                ),
            ],
        ),
    ]
