# Generated by Django 4.2.2 on 2023-06-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="quantity",
            field=models.IntegerField(db_column="quantity_game", null=True),
        ),
    ]
